plugin:
  name: custom-data-type-gfbio
  version: 1.0
  url: https://github.com/programmfabrik/fylr-custom-data-type-gfbio
  displayname:
    de-DE: GFBIO-Verknüpfung
    en-US: GFBIO-Referencing
  info:
    de-DE: Stellt Verknüpfungen zum gfbio-Terminology-Service her
    en-US: Links to the gfbio-Terminology-Service
  l10n: l10n/customDataTypeGfbio.csv
  webfrontend:
    url: customDataTypeGfbio.js
    css: customDataTypeGfbio.css
    dependencies:
      - commons-library

base_url_prefix: "webfrontend"

custom_types:
  gfbio:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptSource:
        type: text
      conceptAncestors:
        type: text
      facetTerm:
        type: text_l10n
    config:
      schema:
        - name: vocabulary_notation
          parameters:
            value:
              type: text
      mask:
        - name: editor_style
          parameters:
            value:
              type: select
              options: ["popover", "popover_treeview"]
        - name: editor_display
          parameters:
            value:
              type: select
              options: ["default", "condensed"]
        - name: overwrite_ontology_configuration
          parameters:
            value:
              type: text
    update:
      plugin_user:
        reference: system:root
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/updater/GfbioUpdater.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 1
      expires_days: 1

base_config:
  - name: endpointurl
    group: endpointurl
    parameters:
      endpointurl:
        type: text
        position: 0
  - name: apikey
    group: apikey
    parameters:
      apikey:
        type: text
        position: 1
  - name: update_gfbio
    group: update_custom_data_type
    parameters:
      restrict_time:
        type: bool
        default: false
        position: 2
      from_time:
        type: int
        default: 19
        min: 0
        max: 24
        position: 3
      to_time:
        type: int
        default: 4
        min: 0
        max: 24
        position: 4
